import prisma from "../src/lib/prisma";

/**
 * 验证文章保存逻辑的核心服务函数 (模拟 Server Action)
 */
async function saveArticleInternal(data: {
    userId: string;
    title: string;
    summary?: string;
    keywords: string[];
    optimizedContent: string;
    contentHtml?: string;
}) {
    return await prisma.trackedArticle.create({
        data: {
            userId: data.userId,
            title: data.title,
            summary: data.summary,
            keywords: data.keywords,
            optimizedContent: data.optimizedContent,
            contentHtml: data.contentHtml,
            status: "PENDING",
        },
    });
}

async function verifyArticleSave() {
    console.log("🔍 [QA] Starting Article Persistence Verification...");

    try {
        // 1. 获取测试用户 (杰克)
        const user = await prisma.user.findFirst({
            where: { email: "jack47.chn@gmail.com" }
        });

        if (!user) {
            throw new Error("Test user not found. Please run verify-auth.ts first.");
        }
        console.log(`✅ [User] Using user: ${user.email} (${user.id})`);

        // 2. 模拟保存一篇文章
        const testArticle = {
            userId: user.id,
            title: "Test AI Article " + new Date().getTime(),
            summary: "This is a test summary for SEO.",
            keywords: ["SEO", "AI Writing", "STP"],
            optimizedContent: "## Hello World\nThis is the content generated by Aladdin.",
            contentHtml: "<h2>Hello World</h2><p>This is the content generated by Aladdin.</p>"
        };

        console.log("🚀 [Action] Saving article to database...");
        const saved = await saveArticleInternal(testArticle);
        
        console.log(`✅ [DB] Article saved successfully. ID: ${saved.id}`);

        // 3. 验证数据一致性
        const fetched = await prisma.trackedArticle.findUnique({
            where: { id: saved.id }
        });

        if (fetched?.title === testArticle.title && fetched?.summary === testArticle.summary) {
            console.log("✅ [Data] Consistency check passed.");
        } else {
            throw new Error("Data consistency check failed!");
        }

        // 4. 清理测试数据 (可选，但为了保持数据库整洁建议执行)
        await prisma.trackedArticle.delete({ where: { id: saved.id } });
        console.log("🧹 [Cleanup] Test data removed.");

        console.log("\n✨ [QA] Article Persistence Verification PASSED.");
    } catch (error) {
        console.error("\n❌ [QA] Verification FAILED:");
        console.error(error);
        process.exit(1);
    }
}

verifyArticleSave();
